### ISSUE TITLE
Workflow, Project, and Milestone DB relationships and connections to company pages

### ISSUE THREAD

**Issue by gabelandau** [gabelandau/macau#22]
- [x] Refactor company-user assignment into company creation/management rather than user creation
- [x] Create workflow-milestone-document relationships
- [x] Display projects & milestones on company dashboard
